### ISSUE TITLE
API: organisation -> organization

### ISSUE THREAD

**Issue by ThiefMaster** [indico/cephalopod#3]
Code usually uses the American flavor of the English language. The API currently expects `organisation` which is not very pretty considering that e.g. the whole Indico codebase uses `organization` internally so it'd be a good idea to rename this here (and also in Indico in the cephalopod API calls!)

**Comment by mvidalgarcia** [comment]
Fixed in https://github.com/indico/cephalopod/commit/d8de94d11c59520e242b36e0de7d4454a4f99ac3
